[package]
name = "url_validator"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.11"
csv = "1.3.0"
reqwest = "0.12.5"
structopt = "0.3.26"
tokio = { version = "1.21.2", features = ["full"] }
tqdm = "0.7.0"
